const cacheName = "cache3"; // Change value to force update

self.addEventListener("install", event => {
	// Kick out the old service worker
	self.skipWaiting();

	event.waitUntil(
		caches.open(cacheName).then(cache => {
			return cache.addAll([

                '/',
                '/index.html',
                '/vanitas-no-carte-anime.gif',
                '/games/index.html',
                '/rickroll2222Google.html',
                '/games/mario64/sm64.us.f3dex2e.wasm',
                '/games/mario64/sm64.us.f3dex2e.js',
                '/games/mario64/index.html',
                '/games/Paper Minecraft v11.html',
                '/200w.gif',
		'/games/doodle-jump/doodle.png',
		'/games/doodle-jump/index.html',
		'/games/doodle-jump/main.js',
		'/games/doodle-jump/sprites.png',
		'/games/doodle-jump/style.css',
		'/Slope-Game/Build/SlopeBuild.data.gz',
		'/Slope-Game/Build/SlopeBuild.framework.js.gz',
		'/Slope-Game/Build/SlopeBuild.loader.js',
		'/Slope-Game/Build/SlopeBuild.wasm.gz',
		'/Slope-Game/TemplateData/style.css',
		'/Slope-Game/TemplateData/favicon.ico',
		'/Slope-Game/TemplateData/fullscreen-button.png',
		'/Slope-Game/TemplateData/progress-bar-empty-dark.png',
		'/Slope-Game/TemplateData/progress-bar-full-dark.png',
		'/Slope-Game/TemplateData/unity-logo-dark.png',
		'/Slope-Game/TemplateData/webgl-logo.png',
		'/Slope-Game/index.html',
		'/games/baldis-basics/TemplateData/progressEmpty.Dark.png',
		'/games/baldis-basics/TemplateData/progressFull.Dark.png',
		'/games/baldis-basics/TemplateData/progressLogo.Dark.png',
		'/games/baldis-basics/TemplateData/style.css',
		'/games/baldis-basics/TemplateData/UnityProgress.js',
		'/games/baldis-basics/unity/baldi.data.unityweb',
		'/games/baldis-basics/unity/baldi.wasm.code.unityweb',
		'/games/baldis-basics/unity/baldi.wasm.framework.unityweb',
		'/games/baldis-basics/baldi.js',
		'/games/baldis-basics/baldi.json',
		'/games/baldis-basics/firebase-app.js',
		'/games/baldis-basics/index.html',
		'/games/baldis-basics/splash.png',
		'/games/minecraft.html',
		'/rickroll.gif',
		'/subway.gif',
		'/credit.html',
		'/style.css',
		'/safari-pinned-tab.svg',
		'/manifest.json',
		'/favicon.ico',
		'/apple-touch-icon.png',
		'/favicon-32x32.png',
		'/favicon-16x16.png',
		'/mstile-150x150.png',
		'/browserconfig.xml',
		'/MCPEweb/index.html',
		'/MCPEweb/index.wasm',
		'/MCPEweb/index.js',
		'/MCPEweb/manifest.json',
		'/MCPEweb/mc_platform.js',
		'/MCPEweb/shell.html',
		'/MCPEweb/index.data',
		'/roblox/index.html',
		'/roblox/rblx.js',
		'/roblox/rblx.wasm',
		'/roblox/WebBlox.png',
		'/roblox/favicon.ico',
		'/roblox/favicon.png',
		'/roblox/coi-serviceworker.js',
		'/roblox/rblx.data.0',
		'/roblox/rblx.data.1',
		'/roblox/rblx.data.2',
		'/roblox/rblx.data.3',
		'/roblox/rblx.data.4',
		'/roblox/rblx.data.5',
		'/roblox/rblx.data.6',
		'/roblox/rblx.data.7',
		'/roblox/rblx.data.8',
		'/roblox/rblx.data.9',
		'/roblox/rblx.data.10',
		'/roblox/rblx.data.11',
		'/roblox/archive/index.html',
		'/games/minecraft-classic/index.html',
		'/games/minecraft-classic/assets/js/app.js',
		'/games/minecraft-classic/assets/js/RandomLevelWorker.js',
		'/games/minecraft-classic/assets/fonts/minecraftfont.ttf',
		'/games/minecraft-classic/assets/fonts/minecraftfont.woff',
		'/games/minecraft-classic/assets/fonts/minecraftfont.woff2',
		'/games/minecraft-classic/assets/css/style.css',
		'/games/pvz/index.html',
		'/games/pvz/pvz.js',
		'/games/pvz/pvz.wasm',
		'/games/pvz/main.pak.part1',
		'/games/pvz/main.pak.part2',
		'/games/pvz/main.pak.part3',
		'/games/pvz/properties/default.xml',
		'/games/pvz/properties/Layout.xml',
		'/games/pvz/properties/partner.xml',
		'/games/pvz/properties/partner.xml.sig',
		'/games/pvz/properties/partner_logo.jpg',

                /* Root-level missing assets */
                '/background.js',
                '/android-chrome-192x192.png',
                '/android-chrome-512x512.png',
                '/site.webmanifest',
                '/old.gif',
                '/7d2a9fca264faa93561f72b5fc885fec.gif',
                '/test.html',
                '/guess what.html',
                '/guesswhat.html',

                /* SonicManiaWeb */
                '/SonicManiaWeb/index.html',
                '/SonicManiaWeb/RSDKv5.html',
                '/SonicManiaWeb/RSDKv5.js',
                '/SonicManiaWeb/RSDKv5.wasm',

                /* stardew-wasm */
                '/stardew-wasm/index.html',
                '/stardew-wasm/game.js',
                '/stardew-wasm/robots.txt',
                '/stardew-wasm/_framework/blazor.boot.json',
                '/stardew-wasm/_framework/dotnet.js',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm0',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm1',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm2',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm.count',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm0',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm1',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm2',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm.count',
                '/stardew-wasm/_framework/dotnet.native.rdr2oxwy28.js',
                '/stardew-wasm/_framework/dotnet.native.vgmtf3jg2i.js',
                '/stardew-wasm/_framework/dotnet.runtime.2hocyfcbj2.js',
                '/stardew-wasm/_framework/FNA.19mbt6y4zi.wasm',
                '/stardew-wasm/_framework/icudt_CJK.tjcz0u77k5.dat',
                '/stardew-wasm/_framework/icudt_EFIGS.tptq2av103.dat',
                '/stardew-wasm/_framework/icudt_no_CJK.lfu7j35m59.dat',
                '/stardew-wasm/_framework/mscorlib.emnk2ck1oc.wasm',
                '/stardew-wasm/_framework/stardew.mlmc2d2oiq.wasm',
                '/stardew-wasm/_framework/stardew.oo74tgnf8n.wasm',
                '/stardew-wasm/_framework/System.Collections.Concurrent.qlhbjf9bos.wasm',
                '/stardew-wasm/_framework/System.Collections.ds5bgcrsdt.wasm',
                '/stardew-wasm/_framework/System.Collections.NonGeneric.5ryvt8698k.wasm',
                '/stardew-wasm/_framework/System.Collections.Specialized.tmjmwnow7m.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.5keg7c7hvo.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.Primitives.bm6ff8kzw2.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.TypeConverter.cn42j6wulu.wasm',
                '/stardew-wasm/_framework/System.Console.l99dsd4m11.wasm',
                '/stardew-wasm/_framework/System.Core.hbtpiioy7n.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.Core.t7f9cy4ve8.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.Interfaces.osqgeneoh8.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.xxHash.3x25n82v9o.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.DiagnosticSource.y73u0d5hpg.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.StackTrace.ckqu3su6df.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.TraceSource.5xvfalz2uw.wasm',
                '/stardew-wasm/_framework/System.dqfxtvioy0.wasm',
                '/stardew-wasm/_framework/System.IO.FileSystem.DriveInfo.vbzmyb4uon.wasm',
                '/stardew-wasm/_framework/System.Linq.Expressions.a1ekmxa1x7.wasm',
                '/stardew-wasm/_framework/System.Linq.hpp1e2tx80.wasm',
                '/stardew-wasm/_framework/System.Net.Http.9945t64114.wasm',
                '/stardew-wasm/_framework/System.Net.NameResolution.y8ux167r4l.wasm',
                '/stardew-wasm/_framework/System.Net.NetworkInformation.wwt8ybvxyv.wasm',
                '/stardew-wasm/_framework/System.Net.Primitives.7jtotj7lx8.wasm',
                '/stardew-wasm/_framework/System.Net.Requests.xoa992kozt.wasm',
                '/stardew-wasm/_framework/System.Net.Sockets.zuwg69fdmh.wasm',
                '/stardew-wasm/_framework/System.Net.WebHeaderCollection.e4ybain77t.wasm',
                '/stardew-wasm/_framework/System.Numerics.o4368phbk9.wasm',
                '/stardew-wasm/_framework/System.ObjectModel.t7b51rllx3.wasm',
                '/stardew-wasm/_framework/System.Private.CoreLib.i8z3vksxlw.wasm',
                '/stardew-wasm/_framework/System.Private.Uri.d0kivwxqf4.wasm',
                '/stardew-wasm/_framework/System.Private.Xml.1op9gajsl5.wasm',
                '/stardew-wasm/_framework/System.Reflection.Emit.Lightweight.6xjxglsw9x.wasm',
                '/stardew-wasm/_framework/System.Runtime.ryq7dzr77n.wasm',
                '/stardew-wasm/_framework/System.Runtime.InteropServices.9p381fkygi.wasm',
                '/stardew-wasm/_framework/System.Runtime.InteropServices.JavaScript.zpx83ctob5.wasm',
                '/stardew-wasm/_framework/System.Runtime.Numerics.ptgadehh8b.wasm',
                '/stardew-wasm/_framework/System.Runtime.Serialization.Formatters.j6cxnl7v8o.wasm',
                '/stardew-wasm/_framework/System.Security.Cryptography.xa1zdy1r7q.wasm',
                '/stardew-wasm/_framework/System.Text.Encoding.Extensions.qunib489dc.wasm',
                '/stardew-wasm/_framework/System.Text.RegularExpressions.aj81zx8ihl.wasm',
                '/stardew-wasm/_framework/System.Threading.p7kqw56j1g.wasm',
                '/stardew-wasm/_framework/System.Threading.Thread.qjvwg8fg4h.wasm',
                '/stardew-wasm/_framework/System.Xml.ReaderWriter.jdtq43bqu8.wasm',
                '/stardew-wasm/_framework/System.Xml.XmlSerializer.e5uisw7343.wasm',
                '/stardew-wasm/Content.tar.count',
                '/stardew-wasm/Content.tar00',
                '/stardew-wasm/Content.tar01',
                '/stardew-wasm/Content.tar02',
                '/stardew-wasm/Content.tar03',
                '/stardew-wasm/ContentAudio.tar.count',
                '/stardew-wasm/ContentAudio.tar00',
                '/stardew-wasm/ContentAudio.tar01',
                '/stardew-wasm/ContentAudio.tar02',
                '/stardew-wasm/ContentAudio.tar03',
                '/stardew-wasm/ContentAudio.tar04',
                '/stardew-wasm/ContentAudio.tar05',
                '/stardew-wasm/ContentAudio.tar06',
                '/stardew-wasm/ContentAudio.tar07',
                '/stardew-wasm/ContentAudio.tar08',
                '/stardew-wasm/ContentAudio.tar09',
                '/stardew-wasm/ContentAudio.tar10',

                /* games/20-Crossy-Road-Game */
                '/games/20-Crossy-Road-Game/index.html',
                '/games/20-Crossy-Road-Game/script.js',
                '/games/20-Crossy-Road-Game/style.css',

                /* games/2048 */
                '/games/2048/2048/index.html',
                '/games/2048/2048/favicon.ico',
                '/games/2048/2048/js/animframe_polyfill.js',
                '/games/2048/2048/js/application.js',
                '/games/2048/2048/js/bind_polyfill.js',
                '/games/2048/2048/js/classlist_polyfill.js',
                '/games/2048/2048/js/game_manager.js',
                '/games/2048/2048/js/grid.js',
                '/games/2048/2048/js/html_actuator.js',
                '/games/2048/2048/js/keyboard_input_manager.js',
                '/games/2048/2048/js/local_storage_manager.js',
                '/games/2048/2048/js/tile.js',
                '/games/2048/2048/style/main.css',
                '/games/2048/2048/style/fonts/clear-sans.css',
                '/games/2048/2048/style/fonts/ClearSans-Bold-webfont.woff',
                '/games/2048/2048/style/fonts/ClearSans-Regular-webfont.woff',

                /* games/2048m */
                '/games/2048m/index.html',
                '/games/2048m/favicon.ico',
                '/games/2048m/js/animframe_polyfill.js',
                '/games/2048m/js/application.js',
                '/games/2048m/js/auto_move.js',
                '/games/2048m/js/bind_polyfill.js',
                '/games/2048m/js/classlist_polyfill.js',
                '/games/2048m/js/game_manager.js',
                '/games/2048m/js/grid.js',
                '/games/2048m/js/html_actuator.js',
                '/games/2048m/js/keyboard_input_manager.js',
                '/games/2048m/js/local_storage_manager.js',
                '/games/2048m/js/tile.js',
                '/games/2048m/style/main.css',
                '/games/2048m/style/fonts/clear-sans.css',
                '/games/2048m/style/fonts/ClearSans-Bold-webfont.woff',
                '/games/2048m/style/fonts/ClearSans-Regular-webfont.woff',

                /* games/brick-breaker */
                '/games/brick-breaker.html',

                /* games/drivemad */
                '/games/drivemad/index.html',
                '/games/drivemad/favicon.ico',
                '/games/drivemad/logo.jpg',
                '/games/drivemad/Jump_Gamemonetize.js',
                '/games/drivemad/webapp/baloo2.woff',
                '/games/drivemad/webapp/cover.jpg',
                '/games/drivemad/webapp/e.html',
                '/games/drivemad/webapp/fancade.css',
                '/games/drivemad/webapp/index.data',
                '/games/drivemad/webapp/index.js',
                '/games/drivemad/webapp/index.wasm',
                '/games/drivemad/webapp/source_min.js',

                /* games/geometry dash bloodbath */
                '/games/geometry dash bloodbath/index.html',
                '/games/geometry dash bloodbath/Build/UnityLoader.js',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.data.unityweb',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.json',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.wasm.framework.unityweb',
                '/games/geometry dash bloodbath/image/loading.png',
                '/games/geometry dash bloodbath/image/process_bar_back.png',
                '/games/geometry dash bloodbath/image/process_bar_front.png',

                /* games/geometry dash lite */
                '/games/geometry dash lite/index.html',
                '/games/geometry dash lite/Build/UnityLoader.js',
                '/games/geometry dash lite/Build/GeometryDashLite.data.unityweb',
                '/games/geometry dash lite/Build/GeometryDashLite.json',
                '/games/geometry dash lite/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/geometry dash lite/Build/GeometryDashLite.wasm.framework.unityweb',
                '/games/geometry dash lite/image/loading.png',
                '/games/geometry dash lite/image/process_bar_back.png',
                '/games/geometry dash lite/image/process_bar_front.png',

                /* games/geometry jump */
                '/games/geometry jump/index.html',
                '/games/geometry jump/game.css',
                '/games/geometry jump/1games.png',
                '/games/geometry jump/background.png',
                '/games/geometry jump/logo.png',
                '/games/geometry jump/progressBar.png',
                '/games/geometry jump/slider.png',
                '/games/geometry jump/sliderBar.png',
                '/games/geometry jump/Build_geo_jump/UnityLoader.js',
                '/games/geometry jump/Build_geo_jump/geo.data.unityweb',
                '/games/geometry jump/Build_geo_jump/geo.json',
                '/games/geometry jump/Build_geo_jump/geo.wasm.code.unityweb',
                '/games/geometry jump/Build_geo_jump/geo.wasm.framework.unityweb',

                /* games/google-snake */
                '/games/google-snake/index.html',
                '/games/google-snake/favicon.ico',
                '/games/google-snake/js/snakedesktop.js',

                /* games/hypertunnel */
                '/games/hypertunnel/index.html',
                '/games/hypertunnel/Build/UnityLoader.js',
                '/games/hypertunnel/Build/GeometryDashLite.json',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.data.unityweb',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.framework.js.unityweb',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.wasm.unityweb',

                /* games/mari0 */
                '/games/mari0/index.html',
                '/games/mari0/game.data',
                '/games/mari0/game.js',

                /* games/retro-bowl */
                '/games/retro-bowl/index.html',
                '/games/retro-bowl/img/icon.jpg',
                '/games/retro-bowl/img/splash.png',
                '/games/retro-bowl/js/main.js',
                '/games/retro-bowl/html5game/RetroBowl.js',
                '/games/retro-bowl/html5game/code.css',
                '/games/retro-bowl/html5game/splash.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_0.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_1.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_2.png',

                /* games/Rocket-League */
                '/games/Rocket-League/index.html',
                '/games/Rocket-League/build.json',
                '/games/Rocket-League/master-loader.js',
                '/games/Rocket-League/poki.js',
                '/games/Rocket-League/splash.png',
                '/games/Rocket-League/unity.js',
                '/games/Rocket-League/UnityLoader.js',

                /* games/slope-game (lowercase) */
                '/games/slope-game/index.html',
                '/games/slope-game/Build/SlopeBuild.data',
                '/games/slope-game/Build/SlopeBuild.framework.js',
                '/games/slope-game/Build/SlopeBuild.loader.js',
                '/games/slope-game/Build/SlopeBuild.wasm',
                '/games/slope-game/TemplateData/style.css',
                '/games/slope-game/TemplateData/fullscreen-button.png',
                '/games/slope-game/TemplateData/progress-bar-empty-dark.png',
                '/games/slope-game/TemplateData/progress-bar-full-dark.png',
                '/games/slope-game/TemplateData/unity-logo-dark.png',
                '/games/slope-game/TemplateData/webgl-logo.png',

                /* games/smashkarts */
                '/games/smashkarts/index.html',
                '/games/smashkarts/manifest.json',
                '/games/smashkarts/xmlhttprequest-length-computable.min.js',
                '/games/smashkarts/scripts/ad-blocker.js',
                '/games/smashkarts/scripts/ads-adsbygoogle-v2.js',
                '/games/smashkarts/scripts/ads-v2.js',
                '/games/smashkarts/scripts/auth-v3.js',
                '/games/smashkarts/scripts/main-v2.js',
                '/games/smashkarts/images/favicon.png',
                '/games/smashkarts/images/icon-144.png',
                '/games/smashkarts/images/icon-512.png',
                '/games/smashkarts/images/menuBGTile.png',
                '/games/smashkarts/images/overlay.png',
                '/games/smashkarts/images/r.png',
                '/games/smashkarts/images/smashkarts.png',
                '/games/smashkarts/images/SmashKartsBackground.jpg',
                '/games/smashkarts/images/SmashKartsPoster.jpg',

                /* games/SnowRider */
                '/games/SnowRider/index.html',
                '/games/SnowRider/Build/UnityLoader.js',
                '/games/SnowRider/Build/GeometryDashLite.data.unityweb',
                '/games/SnowRider/Build/GeometryDashLite.json',
                '/games/SnowRider/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/SnowRider/Build/GeometryDashLite.wasm.framework.unityweb',

                /* games/spacewave */
                '/games/spacewave/index.html',
                '/games/spacewave/Build/UnityLoader.js',
                '/games/spacewave/Build/GeometryDashLite.data.unityweb',
                '/games/spacewave/Build/GeometryDashLite.json',
                '/games/spacewave/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/spacewave/Build/GeometryDashLite.wasm.framework.unityweb',

                /* games/ST1 */
                '/games/ST1/index.html',

                /* games/subway-surfers-ny */
                '/games/subway-surfers-ny/index.html',
                '/games/subway-surfers-ny/NewYorkIcon.png',
                '/games/subway-surfers-ny/js/boot.js',
                '/games/subway-surfers-ny/js/inflate.min.js',
                '/games/subway-surfers-ny/js/main.js',
                '/games/subway-surfers-ny/js/vendor.js',
                '/games/subway-surfers-ny/js/workers/worker.21cc18ec46e616e4eed8.js',
                '/games/subway-surfers-ny/js/games_lib/ludiAdapter.js',
                '/games/subway-surfers-ny/assets/font/lilita-one.css',
                '/games/subway-surfers-ny/assets/font/lilita-one.woff2',
                '/games/subway-surfers-ny/assets/font/titan-one.css',
                '/games/subway-surfers-ny/assets/font/titan-one.woff2',
                '/games/subway-surfers-ny/assets/data/config.json',
                '/games/subway-surfers-ny/assets/data/strings_en.json',
                '/games/subway-surfers-ny/assets/data/chunks_game.json',
                '/games/subway-surfers-ny/assets/data/chunks_idle.json',
                '/games/subway-surfers-ny/assets/preload/splash_mip.png',
                '/games/subway-surfers-ny/assets/ui/ui.json',
                '/games/subway-surfers-ny/assets/ui/ui.png',

                /* games/tunnelrush */
                '/games/tunnelrush/index.html',
                '/games/tunnelrush/Build/UnityLoader.js',
                '/games/tunnelrush/Build/GeometryDashLite.json',
                '/games/tunnelrush/Build/tunnel_rush_v9data.unityweb',
                '/games/tunnelrush/Build/tunnel_rush_v9wasmcode.unityweb',
                '/games/tunnelrush/Build/tunnel_rush_v9wasmframework.unityweb',

                /* games/worlds-hardest-game */
                '/games/worlds-hardest-game/index.html',
                '/games/worlds-hardest-game/css/style.css',
                '/games/worlds-hardest-game/images/splash.jpg',
                '/games/worlds-hardest-game/images/main_menu.png',
                '/games/worlds-hardest-game/images/main_menu_level_select.png',
                '/games/worlds-hardest-game/images/main_menu_load_game.png',
                '/games/worlds-hardest-game/images/main_menu_play_game.png',
                '/games/worlds-hardest-game/js/bars.js',
                '/games/worlds-hardest-game/js/border.js',
                '/games/worlds-hardest-game/js/buttons.js',
                '/games/worlds-hardest-game/js/canvas.js',
                '/games/worlds-hardest-game/js/checkpoint.js',
                '/games/worlds-hardest-game/js/coins.js',
                '/games/worlds-hardest-game/js/colors.js',
                '/games/worlds-hardest-game/js/enemy.js',
                '/games/worlds-hardest-game/js/finish.js',
                '/games/worlds-hardest-game/js/hotkeys.js',
                '/games/worlds-hardest-game/js/ingame_menu.js',
                '/games/worlds-hardest-game/js/instructions.js',
                '/games/worlds-hardest-game/js/intermission.js',
                '/games/worlds-hardest-game/js/jquery.hotkeys.js',
                '/games/worlds-hardest-game/js/jquery.min.js',
                '/games/worlds-hardest-game/js/key_status.js',
                '/games/worlds-hardest-game/js/level_select.js',
                '/games/worlds-hardest-game/js/main.js',
                '/games/worlds-hardest-game/js/main_menu.js',
                '/games/worlds-hardest-game/js/mobile_controls.js',
                '/games/worlds-hardest-game/js/mouse.js',
                '/games/worlds-hardest-game/js/player.js',
                '/games/worlds-hardest-game/js/preloader.js',
                '/games/worlds-hardest-game/js/sounds.js',
                '/games/worlds-hardest-game/js/timer.js',
                '/games/worlds-hardest-game/js/vars.js',
                '/games/worlds-hardest-game/js/walls.js',

                /* games/worlds-hardest-game-2 */
                '/games/worlds-hardest-game-2/index.html',
                '/games/worlds-hardest-game-2/css/style.css',
                '/games/worlds-hardest-game-2/images/main_menu.png',
                '/games/worlds-hardest-game-2/js/bars.js',
                '/games/worlds-hardest-game-2/js/border.js',
                '/games/worlds-hardest-game-2/js/buttons.js',
                '/games/worlds-hardest-game-2/js/canvas.js',
                '/games/worlds-hardest-game-2/js/checkpoint.js',
                '/games/worlds-hardest-game-2/js/coins.js',
                '/games/worlds-hardest-game-2/js/colors.js',
                '/games/worlds-hardest-game-2/js/doors.js',
                '/games/worlds-hardest-game-2/js/enemy.js',
                '/games/worlds-hardest-game-2/js/finish.js',
                '/games/worlds-hardest-game-2/js/hotkeys.js',
                '/games/worlds-hardest-game-2/js/ingame_menu.js',
                '/games/worlds-hardest-game-2/js/instructions.js',
                '/games/worlds-hardest-game-2/js/intermission.js',
                '/games/worlds-hardest-game-2/js/jquery.hotkeys.js',
                '/games/worlds-hardest-game-2/js/jquery.min.js',
                '/games/worlds-hardest-game-2/js/key_status.js',
                '/games/worlds-hardest-game-2/js/keys.js',
                '/games/worlds-hardest-game-2/js/level_select.js',
                '/games/worlds-hardest-game-2/js/main.js',
                '/games/worlds-hardest-game-2/js/main_menu.js',
                '/games/worlds-hardest-game-2/js/mobile_controls.js',
                '/games/worlds-hardest-game-2/js/mouse.js',
                '/games/worlds-hardest-game-2/js/player.js',
                '/games/worlds-hardest-game-2/js/preloader.js',
                '/games/worlds-hardest-game-2/js/sounds.js',
                '/games/worlds-hardest-game-2/js/timer.js',
                '/games/worlds-hardest-game-2/js/vars.js',
                '/games/worlds-hardest-game-2/js/walls.js',

                '/games/worlds-hardest-game-2/sounds/sfx_bounce0.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_bounce1.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_checkpoint.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_click.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_coin.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_die.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_intermission.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_win.mp3',
                '/games/worlds-hardest-game-2/the-worlds-hardest-game-2.jpg',

                /* games/hl-main */
                '/games/hl-main/index.html',
                '/games/hl-main/404.html',
                '/games/hl-main/xash.html',
                '/games/hl-main/1.js',
                '/games/hl-main/browserfs.min.js',
                '/games/hl-main/client.js',
                '/games/hl-main/firebug-lite-compressed.js',
                '/games/hl-main/menu.js',
                '/games/hl-main/mods.js',
                '/games/hl-main/mods-offline.js',
                '/games/hl-main/server.js',
                '/games/hl-main/music.mp3',
                '/games/hl-main/home.png',
                '/games/hl-main/icon.png',
                '/games/hl-main/xd.png',
                '/games/hl-main/favicon.ico',
                '/games/hl-main/xash.html.mem',
                '/games/hl-main/xash.js',
                '/games/hl-main/xash.appcache',
                '/games/hl-main/xash2.appcache',
                '/games/hl-main/xash.webmanifest'

		]);
		})
	);
});

self.addEventListener("activate", event => {
	// Delete any non-current cache
	event.waitUntil(
		caches.keys().then(keys => {
			return Promise.all(
				keys.map(key => {
					if (![cacheName].includes(key)) {
						return caches.delete(key);
					}
				})
			)
		})
	);
});

// Offline-first, cache-first strategy
// Kick off two asynchronous requests, one to the cache and one to the network
// If there's a cached version available, use it, but fetch an update for next time.
// Gets data on screen as quickly as possible, then updates once the network has returned the latest data. 
self.addEventListener("fetch", event => {
	event.respondWith(
		caches.open(cacheName).then(cache => {
			return cache.match(event.request).then(response => {
				return response || fetch(event.request).then(networkResponse => {
					cache.put(event.request, networkResponse.clone());
					return networkResponse;
				});
			})
		})
	);
});
