const cacheName = "cache3"; // Change value to force update

self.addEventListener("install", event => {
	// Kick out the old service worker
	self.skipWaiting();

	event.waitUntil(
		caches.open(cacheName).then(cache => {
			return cache.addAll([

                '/',
                '/index.html',
                'https://files.catbox.moe/adef69.webp',
                '/vanitas-no-carte-anime.gif',
                '/games/index.html',
                '/rickroll2222Google.html',
                '/games/mario64/sm64.us.f3dex2e.wasm',
                '/games/mario64/sm64.us.f3dex2e.js',
                '/games/mario64/index.html',
                '/games/Paper Minecraft v11.html',
                '/200w.gif',
		'/games/doodle-jump/doodle.png',
		'/games/doodle-jump/index.html',
		'/games/doodle-jump/main.js',
		'/games/doodle-jump/sprites.png',
		'/games/doodle-jump/style.css',
		'/Slope-Game/Build/SlopeBuild.data.gz',
		'/Slope-Game/Build/SlopeBuild.framework.js.gz',
		'/Slope-Game/Build/SlopeBuild.loader.js',
		'/Slope-Game/Build/SlopeBuild.wasm.gz',
		'/Slope-Game/TemplateData/style.css',
		'/Slope-Game/TemplateData/favicon.ico',
		'/Slope-Game/TemplateData/fullscreen-button.png',
		'/Slope-Game/TemplateData/progress-bar-empty-dark.png',
		'/Slope-Game/TemplateData/progress-bar-full-dark.png',
		'/Slope-Game/TemplateData/unity-logo-dark.png',
		'/Slope-Game/TemplateData/webgl-logo.png',
		'/Slope-Game/index.html',
		'/games/baldis-basics/TemplateData/progressEmpty.Dark.png',
		'/games/baldis-basics/TemplateData/progressFull.Dark.png',
		'/games/baldis-basics/TemplateData/progressLogo.Dark.png',
		'/games/baldis-basics/TemplateData/style.css',
		'/games/baldis-basics/TemplateData/UnityProgress.js',
		'/games/baldis-basics/unity/baldi.data.unityweb',
		'/games/baldis-basics/unity/baldi.wasm.code.unityweb',
		'/games/baldis-basics/unity/baldi.wasm.framework.unityweb',
		'/games/baldis-basics/baldi.js',
		'/games/baldis-basics/baldi.json',
		'/games/baldis-basics/firebase-app.js',
		'/games/baldis-basics/index.html',
		'/games/baldis-basics/splash.png',
		'/games/minecraft.html',
		'/credit.html',
		'/style.css',
		'/safari-pinned-tab.svg',
		'/manifest.json',
		'/favicon.ico',
		'/apple-touch-icon.png',
		'/favicon-32x32.png',
		'/favicon-16x16.png',
		'/mstile-150x150.png',
		'/browserconfig.xml',
		'/MCPEweb/index.html',
		'/MCPEweb/index.wasm',
		'/MCPEweb/index.js',
		'/MCPEweb/manifest.json',
		'/MCPEweb/mc_platform.js',
		'/MCPEweb/shell.html',
		'/MCPEweb/index.data',
		'/MCPEweb/sw.js',
		'/roblox/index.html',
		'/roblox/rblx.js',
		'/roblox/rblx.wasm',
		'/roblox/WebBlox.png',
		'/roblox/favicon.png',
		'/roblox/coi-serviceworker.js',
		'/roblox/rblx.data.0',
		'/roblox/rblx.data.1',
		'/roblox/rblx.data.2',
		'/roblox/rblx.data.3',
		'/roblox/rblx.data.4',
		'/roblox/rblx.data.5',
		'/roblox/rblx.data.6',
		'/roblox/rblx.data.7',
		'/roblox/rblx.data.8',
		'/roblox/rblx.data.9',
		'/roblox/rblx.data.10',
		'/roblox/rblx.data.11',
		'/roblox/archive/index.html',
		'/games/minecraft-classic/index.html',
		'/games/minecraft-classic/assets/js/app.js',
		'/games/minecraft-classic/assets/js/RandomLevelWorker.js',
		'/games/minecraft-classic/assets/fonts/minecraftfont.ttf',
		'/games/minecraft-classic/assets/fonts/minecraftfont.woff',
		'/games/minecraft-classic/assets/css/style.css',
		'/games/pvz/index.html',
		'/games/pvz/pvz.js',
		'/games/pvz/pvz.wasm',
		'/games/pvz/main.pak.part1',
		'/games/pvz/main.pak.part2',
		'/games/pvz/main.pak.part3',
		'/games/pvz/properties/default.xml',
		'/games/pvz/properties/Layout.xml',
		'/games/pvz/properties/partner.xml',
		'/games/pvz/properties/partner.xml.sig',
		'/games/pvz/properties/partner_logo.jpg',

                /* Root-level missing assets */
                '/background.js',
                '/android-chrome-192x192.png',
                '/android-chrome-512x512.png',
                '/site.webmanifest',
                '/old.gif',
                '/7d2a9fca264faa93561f72b5fc885fec.gif',
                '/test.html',
                '/guess what.html',
                '/guesswhat.html',

                /* SonicManiaWeb */
                '/games/SonicManiaWeb/index.html',
                '/games/SonicManiaWeb/RSDKv5.html',
                '/games/SonicManiaWeb/RSDKv5.js',
                '/games/SonicManiaWeb/RSDKv5.wasm',
                '/games/SonicManiaWeb/Data.js',
                '/games/SonicManiaWeb/Data.data.part0',
                '/games/SonicManiaWeb/Data.data.part1',
                '/games/SonicManiaWeb/Data.data.part2',
                '/games/SonicManiaWeb/Data.data.part3',
                '/games/SonicManiaWeb/Data.data.part4',
                '/games/SonicManiaWeb/Data.data.part5',
                '/games/SonicManiaWeb/Data.data.part6',
                '/games/SonicManiaWeb/Data.data.part7',
                '/games/SonicManiaWeb/Data.data.part8',
                '/games/SonicManiaWeb/Data.data.part9',
                '/games/SonicManiaWeb/Data.data.part10',
                '/games/SonicManiaWeb/Data.data.part11',
                '/games/SonicManiaWeb/Data.data.part12',
                '/games/SonicManiaWeb/Data.data.part13',
                '/games/SonicManiaWeb/RSDKv5U.js',
                '/games/SonicManiaWeb/RSDKv5U.wasm',
                '/games/SonicManiaWeb/image_2026-02-26_224423134.png',
                '/games/SonicManiaWeb/image_2026-02-26_224632873.png',
                '/games/SonicManiaWeb/jsdlivr-html/crunchymania.html',

                /* stardew-wasm */
                '/stardew-wasm/index.html',
                '/stardew-wasm/game.js',
                '/stardew-wasm/robots.txt',
                '/stardew-wasm/_framework/blazor.boot.json',
                '/stardew-wasm/_framework/dotnet.js',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm0',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm1',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm2',
                '/stardew-wasm/_framework/dotnet.native.4besgko34q.wasm.count',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm0',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm1',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm2',
                '/stardew-wasm/_framework/dotnet.native.k0dnmixusv.wasm.count',
                '/stardew-wasm/_framework/dotnet.native.rdr2oxwy28.js',
                '/stardew-wasm/_framework/dotnet.native.vgmtf3jg2i.js',
                '/stardew-wasm/_framework/dotnet.runtime.2hocyfcbj2.js',
                '/stardew-wasm/_framework/FNA.19mbt6y4zi.wasm',
                '/stardew-wasm/_framework/icudt_CJK.tjcz0u77k5.dat',
                '/stardew-wasm/_framework/icudt_EFIGS.tptq2av103.dat',
                '/stardew-wasm/_framework/icudt_no_CJK.lfu7j35m59.dat',
                '/stardew-wasm/_framework/mscorlib.emnk2ck1oc.wasm',
                '/stardew-wasm/_framework/stardew.mlmc2d2oiq.wasm',
                '/stardew-wasm/_framework/stardew.oo74tgnf8n.wasm',
                '/stardew-wasm/_framework/System.Collections.Concurrent.qlhbjf9bos.wasm',
                '/stardew-wasm/_framework/System.Collections.ds5bgcrsdt.wasm',
                '/stardew-wasm/_framework/System.Collections.NonGeneric.5ryvt8698k.wasm',
                '/stardew-wasm/_framework/System.Collections.Specialized.tmjmwnow7m.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.5keg7c7hvo.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.Primitives.bm6ff8kzw2.wasm',
                '/stardew-wasm/_framework/System.ComponentModel.TypeConverter.cn42j6wulu.wasm',
                '/stardew-wasm/_framework/System.Console.l99dsd4m11.wasm',
                '/stardew-wasm/_framework/System.Core.hbtpiioy7n.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.Core.t7f9cy4ve8.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.Interfaces.osqgeneoh8.wasm',
                '/stardew-wasm/_framework/System.Data.HashFunction.xxHash.3x25n82v9o.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.DiagnosticSource.y73u0d5hpg.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.StackTrace.ckqu3su6df.wasm',
                '/stardew-wasm/_framework/System.Diagnostics.TraceSource.5xvfalz2uw.wasm',
                '/stardew-wasm/_framework/System.dqfxtvioy0.wasm',
                '/stardew-wasm/_framework/System.IO.FileSystem.DriveInfo.vbzmyb4uon.wasm',
                '/stardew-wasm/_framework/System.Linq.Expressions.a1ekmxa1x7.wasm',
                '/stardew-wasm/_framework/System.Linq.hpp1e2tx80.wasm',
                '/stardew-wasm/_framework/System.Net.Http.9945t64114.wasm',
                '/stardew-wasm/_framework/System.Net.NameResolution.y8ux167r4l.wasm',
                '/stardew-wasm/_framework/System.Net.NetworkInformation.wwt8ybvxyv.wasm',
                '/stardew-wasm/_framework/System.Net.Primitives.7jtotj7lx8.wasm',
                '/stardew-wasm/_framework/System.Net.Requests.xoa992kozt.wasm',
                '/stardew-wasm/_framework/System.Net.Sockets.zuwg69fdmh.wasm',
                '/stardew-wasm/_framework/System.Net.WebHeaderCollection.e4ybain77t.wasm',
                '/stardew-wasm/_framework/System.Numerics.o4368phbk9.wasm',
                '/stardew-wasm/_framework/System.ObjectModel.t7b51rllx3.wasm',
                '/stardew-wasm/_framework/System.Private.CoreLib.i8z3vksxlw.wasm',
                '/stardew-wasm/_framework/System.Private.Uri.d0kivwxqf4.wasm',
                '/stardew-wasm/_framework/System.Private.Xml.1op9gajsl5.wasm',
                '/stardew-wasm/_framework/System.Reflection.Emit.Lightweight.6xjxglsw9x.wasm',
                '/stardew-wasm/_framework/System.Runtime.ryq7dzr77n.wasm',
                '/stardew-wasm/_framework/System.Runtime.InteropServices.9p381fkygi.wasm',
                '/stardew-wasm/_framework/System.Runtime.InteropServices.JavaScript.zpx83ctob5.wasm',
                '/stardew-wasm/_framework/System.Runtime.Numerics.ptgadehh8b.wasm',
                '/stardew-wasm/_framework/System.Runtime.Serialization.Formatters.j6cxnl7v8o.wasm',
                '/stardew-wasm/_framework/System.Security.Cryptography.xa1zdy1r7q.wasm',
                '/stardew-wasm/_framework/System.Text.Encoding.Extensions.qunib489dc.wasm',
                '/stardew-wasm/_framework/System.Text.RegularExpressions.aj81zx8ihl.wasm',
                '/stardew-wasm/_framework/System.Threading.p7kqw56j1g.wasm',
                '/stardew-wasm/_framework/System.Threading.Thread.qjvwg8fg4h.wasm',
                '/stardew-wasm/_framework/System.Xml.ReaderWriter.jdtq43bqu8.wasm',
                '/stardew-wasm/_framework/System.Xml.XmlSerializer.e5uisw7343.wasm',
                '/stardew-wasm/Content.tar.count',
                '/stardew-wasm/Content.tar00',
                '/stardew-wasm/Content.tar01',
                '/stardew-wasm/Content.tar02',
                '/stardew-wasm/Content.tar03',
                '/stardew-wasm/ContentAudio.tar.count',
                '/stardew-wasm/ContentAudio.tar00',
                '/stardew-wasm/ContentAudio.tar01',
                '/stardew-wasm/ContentAudio.tar02',
                '/stardew-wasm/ContentAudio.tar03',
                '/stardew-wasm/ContentAudio.tar04',
                '/stardew-wasm/ContentAudio.tar05',
                '/stardew-wasm/ContentAudio.tar06',
                '/stardew-wasm/ContentAudio.tar07',
                '/stardew-wasm/ContentAudio.tar08',
                '/stardew-wasm/ContentAudio.tar09',
                '/stardew-wasm/ContentAudio.tar10',

                /* games/20-Crossy-Road-Game */
                '/games/20-Crossy-Road-Game/index.html',
                '/games/20-Crossy-Road-Game/script.js',
                '/games/20-Crossy-Road-Game/style.css',

                /* games/2048 */
                '/games/2048/2048/index.html',
                '/games/2048/2048/favicon.ico',
                '/games/2048/2048/js/animframe_polyfill.js',
                '/games/2048/2048/js/application.js',
                '/games/2048/2048/js/bind_polyfill.js',
                '/games/2048/2048/js/classlist_polyfill.js',
                '/games/2048/2048/js/game_manager.js',
                '/games/2048/2048/js/grid.js',
                '/games/2048/2048/js/html_actuator.js',
                '/games/2048/2048/js/keyboard_input_manager.js',
                '/games/2048/2048/js/local_storage_manager.js',
                '/games/2048/2048/js/tile.js',
                '/games/2048/2048/style/main.css',
                '/games/2048/2048/style/fonts/clear-sans.css',
                '/games/2048/2048/style/fonts/ClearSans-Bold-webfont.woff',
                '/games/2048/2048/style/fonts/ClearSans-Regular-webfont.woff',

                /* games/2048m */
                '/games/2048m/index.html',
                '/games/2048m/favicon.ico',
                '/games/2048m/js/animframe_polyfill.js',
                '/games/2048m/js/application.js',
                '/games/2048m/js/auto_move.js',
                '/games/2048m/js/bind_polyfill.js',
                '/games/2048m/js/classlist_polyfill.js',
                '/games/2048m/js/game_manager.js',
                '/games/2048m/js/grid.js',
                '/games/2048m/js/html_actuator.js',
                '/games/2048m/js/keyboard_input_manager.js',
                '/games/2048m/js/local_storage_manager.js',
                '/games/2048m/js/tile.js',
                '/games/2048m/style/main.css',
                '/games/2048m/style/fonts/clear-sans.css',
                '/games/2048m/style/fonts/ClearSans-Bold-webfont.woff',
                '/games/2048m/style/fonts/ClearSans-Regular-webfont.woff',

                /* games/brick-breaker */
                '/games/brick-breaker.html',

                /* games/drivemad */
                '/games/drivemad/index.html',
                '/games/drivemad/favicon.ico',
                '/games/drivemad/logo.jpg',
                '/games/drivemad/Jump_Gamemonetize.js',
                '/games/drivemad/webapp/baloo2.woff',
                '/games/drivemad/webapp/cover.jpg',
                '/games/drivemad/webapp/e.html',
                '/games/drivemad/webapp/fancade.css',
                '/games/drivemad/webapp/index.data',
                '/games/drivemad/webapp/index.js',
                '/games/drivemad/webapp/index.wasm',
                '/games/drivemad/webapp/source_min.js',

                /* games/geometry dash bloodbath */
                '/games/geometry dash bloodbath/index.html',
                '/games/geometry dash bloodbath/Build/UnityLoader.js',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.data.unityweb',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.json',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/geometry dash bloodbath/Build/GeometryDashLite.wasm.framework.unityweb',
                '/games/geometry dash bloodbath/image/loading.png',
                '/games/geometry dash bloodbath/image/process_bar_back.png',
                '/games/geometry dash bloodbath/image/process_bar_front.png',

                /* games/geometry dash lite */
                '/games/geometry dash lite/index.html',
                '/games/geometry dash lite/Build/UnityLoader.js',
                '/games/geometry dash lite/Build/GeometryDashLite.data.unityweb',
                '/games/geometry dash lite/Build/GeometryDashLite.json',
                '/games/geometry dash lite/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/geometry dash lite/Build/GeometryDashLite.wasm.framework.unityweb',
                '/games/geometry dash lite/image/loading.png',
                '/games/geometry dash lite/image/process_bar_back.png',
                '/games/geometry dash lite/image/process_bar_front.png',

                /* games/geometry jump */
                '/games/geometry jump/index.html',
                '/games/geometry jump/game.css',
                '/games/geometry jump/1games.png',
                '/games/geometry jump/background.png',
                '/games/geometry jump/logo.png',
                '/games/geometry jump/progressBar.png',
                '/games/geometry jump/slider.png',
                '/games/geometry jump/sliderBar.png',
                '/games/geometry jump/Build_geo_jump/UnityLoader.js',
                '/games/geometry jump/Build_geo_jump/geo.data.unityweb',
                '/games/geometry jump/Build_geo_jump/geo.json',
                '/games/geometry jump/Build_geo_jump/geo.wasm.code.unityweb',
                '/games/geometry jump/Build_geo_jump/geo.wasm.framework.unityweb',

                /* games/google-snake */
                '/games/google-snake/index.html',
                '/games/google-snake/favicon.ico',
                '/games/google-snake/js/snakedesktop.js',

                /* games/hypertunnel */
                '/games/hypertunnel/index.html',
                '/games/hypertunnel/Build/UnityLoader.js',
                '/games/hypertunnel/Build/GeometryDashLite.json',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.data.unityweb',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.framework.js.unityweb',
                '/games/hypertunnel/Build/hyper-tunnel-v25111801.wasm.unityweb',

                /* games/mari0 */
                '/games/mari0/index.html',
                '/games/mari0/game.data',
                '/games/mari0/game.js',

                /* games/retro-bowl */
                '/games/retro-bowl/index.html',
                '/games/retro-bowl/img/icon.jpg',
                '/games/retro-bowl/img/splash.png',
                '/games/retro-bowl/js/main.js',
                '/games/retro-bowl/html5game/RetroBowl.js',
                '/games/retro-bowl/html5game/code.css',
                '/games/retro-bowl/html5game/splash.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_0.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_1.png',
                '/games/retro-bowl/html5game/RetroBowl_texture_2.png',

                /* games/Rocket-League */
                '/games/Rocket-League/index.html',
                '/games/Rocket-League/build.json',
                '/games/Rocket-League/master-loader.js',
                '/games/Rocket-League/poki.js',
                '/games/Rocket-League/splash.png',
                '/games/Rocket-League/unity.js',
                '/games/Rocket-League/UnityLoader.js',

                /* games/slope-game (lowercase) */
                '/games/slope-game/index.html',
                '/games/slope-game/Build/SlopeBuild.data',
                '/games/slope-game/Build/SlopeBuild.framework.js',
                '/games/slope-game/Build/SlopeBuild.loader.js',
                '/games/slope-game/Build/SlopeBuild.wasm',
                '/games/slope-game/TemplateData/style.css',
                '/games/slope-game/TemplateData/fullscreen-button.png',
                '/games/slope-game/TemplateData/progress-bar-empty-dark.png',
                '/games/slope-game/TemplateData/progress-bar-full-dark.png',
                '/games/slope-game/TemplateData/unity-logo-dark.png',
                '/games/slope-game/TemplateData/webgl-logo.png',

                /* games/smashkarts */
                '/games/smashkarts/index.html',
                '/games/smashkarts/manifest.json',
                '/games/smashkarts/xmlhttprequest-length-computable.min.js',
                '/games/smashkarts/scripts/ad-blocker.js',
                '/games/smashkarts/scripts/ads-adsbygoogle-v2.js',
                '/games/smashkarts/scripts/ads-v2.js',
                '/games/smashkarts/scripts/auth-v3.js',
                '/games/smashkarts/scripts/main-v2.js',
                '/games/smashkarts/images/favicon.png',
                '/games/smashkarts/images/icon-144.png',
                '/games/smashkarts/images/icon-512.png',
                '/games/smashkarts/images/menuBGTile.png',
                '/games/smashkarts/images/overlay.png',
                '/games/smashkarts/images/r.png',
                '/games/smashkarts/images/smashkarts.png',
                '/games/smashkarts/images/SmashKartsBackground.jpg',
                '/games/smashkarts/images/SmashKartsPoster.jpg',

                /* games/SnowRider */
                '/games/SnowRider/index.html',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.data.br',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.framework.js.br',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.loader.js',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.wasm.br',

                /* games/spacewave */
                '/games/spacewave/index.html',
                '/games/spacewave/Build/UnityLoader.js',
                '/games/spacewave/Build/GeometryDashLite.data.unityweb',
                '/games/spacewave/Build/GeometryDashLite.json',
                '/games/spacewave/Build/GeometryDashLite.wasm.code.unityweb',
                '/games/spacewave/Build/GeometryDashLite.wasm.framework.unityweb',

                /* games/ST1 */
                '/games/ST1/index.html',

                /* games/subway-surfers-ny */
                '/games/subway-surfers-ny/index.html',
                '/games/subway-surfers-ny/NewYorkIcon.png',
                '/games/subway-surfers-ny/js/boot.js',
                '/games/subway-surfers-ny/js/inflate.min.js',
                '/games/subway-surfers-ny/js/main.js',
                '/games/subway-surfers-ny/js/vendor.js',
                '/games/subway-surfers-ny/js/workers/worker.21cc18ec46e616e4eed8.js',
                '/games/subway-surfers-ny/js/games_lib/ludiAdapter.js',
                '/games/subway-surfers-ny/assets/font/lilita-one.css',
                '/games/subway-surfers-ny/assets/font/lilita-one.woff2',
                '/games/subway-surfers-ny/assets/font/titan-one.css',
                '/games/subway-surfers-ny/assets/font/titan-one.woff2',
                '/games/subway-surfers-ny/assets/data/config.json',
                '/games/subway-surfers-ny/assets/data/strings_en.json',
                '/games/subway-surfers-ny/assets/data/chunks_game.json',
                '/games/subway-surfers-ny/assets/data/chunks_idle.json',
                '/games/subway-surfers-ny/assets/preload/splash_mip.png',
                '/games/subway-surfers-ny/assets/ui/ui.json',
                '/games/subway-surfers-ny/assets/ui/ui.png',

                /* games/tunnelrush */
                '/games/tunnelrush/index.html',
                '/games/tunnelrush/Build/UnityLoader.js',
                '/games/tunnelrush/Build/GeometryDashLite.json',
                '/games/tunnelrush/Build/tunnel_rush_v9data.unityweb',
                '/games/tunnelrush/Build/tunnel_rush_v9wasmcode.unityweb',
                '/games/tunnelrush/Build/tunnel_rush_v9wasmframework.unityweb',

                /* games/worlds-hardest-game */
                '/games/worlds-hardest-game/index.html',
                '/games/worlds-hardest-game/css/style.css',
                '/games/worlds-hardest-game/images/splash.jpg',
                '/games/worlds-hardest-game/images/main_menu.png',
                '/games/worlds-hardest-game/images/main_menu_level_select.png',
                '/games/worlds-hardest-game/images/main_menu_load_game.png',
                '/games/worlds-hardest-game/images/main_menu_play_game.png',
                '/games/worlds-hardest-game/js/bars.js',
                '/games/worlds-hardest-game/js/border.js',
                '/games/worlds-hardest-game/js/buttons.js',
                '/games/worlds-hardest-game/js/canvas.js',
                '/games/worlds-hardest-game/js/checkpoint.js',
                '/games/worlds-hardest-game/js/coins.js',
                '/games/worlds-hardest-game/js/colors.js',
                '/games/worlds-hardest-game/js/enemy.js',
                '/games/worlds-hardest-game/js/finish.js',
                '/games/worlds-hardest-game/js/hotkeys.js',
                '/games/worlds-hardest-game/js/ingame_menu.js',
                '/games/worlds-hardest-game/js/instructions.js',
                '/games/worlds-hardest-game/js/intermission.js',
                '/games/worlds-hardest-game/js/jquery.hotkeys.js',
                '/games/worlds-hardest-game/js/jquery.min.js',
                '/games/worlds-hardest-game/js/key_status.js',
                '/games/worlds-hardest-game/js/level_select.js',
                '/games/worlds-hardest-game/js/main.js',
                '/games/worlds-hardest-game/js/main_menu.js',
                '/games/worlds-hardest-game/js/mobile_controls.js',
                '/games/worlds-hardest-game/js/mouse.js',
                '/games/worlds-hardest-game/js/player.js',
                '/games/worlds-hardest-game/js/preloader.js',
                '/games/worlds-hardest-game/js/sounds.js',
                '/games/worlds-hardest-game/js/timer.js',
                '/games/worlds-hardest-game/js/vars.js',
                '/games/worlds-hardest-game/js/walls.js',

                /* games/worlds-hardest-game-2 */
                '/games/worlds-hardest-game-2/index.html',
                '/games/worlds-hardest-game-2/css/style.css',
                '/games/worlds-hardest-game-2/images/main_menu.png',
                '/games/worlds-hardest-game-2/js/bars.js',
                '/games/worlds-hardest-game-2/js/border.js',
                '/games/worlds-hardest-game-2/js/buttons.js',
                '/games/worlds-hardest-game-2/js/canvas.js',
                '/games/worlds-hardest-game-2/js/checkpoint.js',
                '/games/worlds-hardest-game-2/js/coins.js',
                '/games/worlds-hardest-game-2/js/colors.js',
                '/games/worlds-hardest-game-2/js/doors.js',
                '/games/worlds-hardest-game-2/js/enemy.js',
                '/games/worlds-hardest-game-2/js/finish.js',
                '/games/worlds-hardest-game-2/js/hotkeys.js',
                '/games/worlds-hardest-game-2/js/ingame_menu.js',
                '/games/worlds-hardest-game-2/js/instructions.js',
                '/games/worlds-hardest-game-2/js/intermission.js',
                '/games/worlds-hardest-game-2/js/jquery.hotkeys.js',
                '/games/worlds-hardest-game-2/js/jquery.min.js',
                '/games/worlds-hardest-game-2/js/key_status.js',
                '/games/worlds-hardest-game-2/js/keys.js',
                '/games/worlds-hardest-game-2/js/level_select.js',
                '/games/worlds-hardest-game-2/js/main.js',
                '/games/worlds-hardest-game-2/js/main_menu.js',
                '/games/worlds-hardest-game-2/js/mobile_controls.js',
                '/games/worlds-hardest-game-2/js/mouse.js',
                '/games/worlds-hardest-game-2/js/player.js',
                '/games/worlds-hardest-game-2/js/preloader.js',
                '/games/worlds-hardest-game-2/js/sounds.js',
                '/games/worlds-hardest-game-2/js/timer.js',
                '/games/worlds-hardest-game-2/js/vars.js',
                '/games/worlds-hardest-game-2/js/walls.js',

                '/games/worlds-hardest-game-2/sounds/sfx_bounce0.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_bounce1.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_checkpoint.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_click.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_coin.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_die.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_intermission.mp3',
                '/games/worlds-hardest-game-2/sounds/sfx_win.mp3',
                '/games/worlds-hardest-game-2/the-worlds-hardest-game-2.jpg',

                /* games/hl-main */
                '/games/hl-main/index.html',
                '/games/hl-main/404.html',
                '/games/hl-main/xash.html',
                '/games/hl-main/1.js',
                '/games/hl-main/browserfs.min.js',
                '/games/hl-main/client.js',
                '/games/hl-main/firebug-lite-compressed.js',
                '/games/hl-main/menu.js',
                '/games/hl-main/mods.js',
                '/games/hl-main/mods-offline.js',
                '/games/hl-main/server.js',
                '/games/hl-main/music.mp3',
                '/games/hl-main/home.png',
                '/games/hl-main/icon.png',
                '/games/hl-main/xd.png',
                '/games/hl-main/favicon.ico',
                '/games/hl-main/xash.html.mem',
                '/games/hl-main/xash.js',
                '/games/hl-main/xash.appcache',
                '/games/hl-main/xash2.appcache',
                '/games/hl-main/xash.webmanifest',

                /* Root-level missing deployable assets */
                '/Untitled drawing (3).png',
                '/funi69',
                '/t',

                /* games/ root pages */
                '/games/fortnite.html',
                '/games/roblox.html',
                '/games/stardewvalley.html',

                /* games/ST1/Build */
                '/games/ST1/Build/UnityLoader.js',
                '/games/ST1/Build/ST1.json',
                '/games/ST1/Build/ST1.data.unityweb',
                '/games/ST1/Build/ST1.asm.memory.unityweb',
                '/games/ST1/Build/ST1.asm.framework.unityweb',
                '/games/ST1/Build/ST1.asm.code.unityweb',

                /* games/SnowRider (replace incorrect GeometryDashLite refs) */
                '/games/SnowRider/webglScreen.js',
                '/games/SnowRider/TemplateData/style.css',
                '/games/SnowRider/TemplateData/logo.png',
                '/games/SnowRider/TemplateData/gears.gif',
                '/games/SnowRider/TemplateData/gamebreak.js',
                '/games/SnowRider/TemplateData/favicon.ico',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.data.br',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.framework.js.br',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.loader.js',
                '/games/SnowRider/Build/snowrider3d_y8_32bt_1_4.wasm.br',

                /* fnaf/1 */
                '/fnaf/1/index.html',
                '/fnaf/1/favicon.ico',
                '/fnaf/1/resources/vignette.png',
                '/fnaf/1/resources/title.png',
                '/fnaf/1/resources/office.png',
                '/fnaf/1/resources/launcher-text.png',
                '/fnaf/1/resources/background.gif',
                '/fnaf/1/resources/animatronic.png',
                '/fnaf/1/src/Runtime.js',
                '/fnaf/1/src/resources.zip.part1',
                '/fnaf/1/src/resources.zip.part2',
                '/fnaf/1/src/resources.zip.part3',
                '/fnaf/1/src/resources.zip.part4',
                '/fnaf/1/src/resources.zip.part5',
                '/fnaf/1/src/resources.zip.part6',
                '/fnaf/1/src/resources.zip.part7',
                '/fnaf/1/src/resources.zip.part8',
                '/fnaf/1/src/resources.zip.part9',
                '/fnaf/1/src/resources.zip.part10',
                '/fnaf/1/src/resources.zip.part11',
                '/fnaf/1/src/resources.zip.part12',
                '/fnaf/1/src/resources.zip.part13',
                '/fnaf/1/src/resources.zip.part14',
                '/fnaf/1/src/resources.zip.part15',
                '/fnaf/1/src/resources.zip.part16',
                '/fnaf/1/src/resources.zip.part17',
                '/fnaf/1/src/resources.zip.part18',
                '/fnaf/1/src/resources.zip.part19',
                '/fnaf/1/src/resources.zip.part20',

                /* fnaf/2 */
                '/fnaf/2/index.html',
                '/fnaf/2/favicon.ico',
                '/fnaf/2/resources/vignette.png',
                '/fnaf/2/resources/title.png',
                '/fnaf/2/resources/office.png',
                '/fnaf/2/resources/launcher-text.png',
                '/fnaf/2/resources/background.gif',
                '/fnaf/2/resources/animatronic.png',
                '/fnaf/2/src/Runtime.js',
                '/fnaf/2/src/resources.zip.part1',
                '/fnaf/2/src/resources.zip.part2',
                '/fnaf/2/src/resources.zip.part3',
                '/fnaf/2/src/resources.zip.part4',
                '/fnaf/2/src/resources.zip.part5',
                '/fnaf/2/src/resources.zip.part6',
                '/fnaf/2/src/resources.zip.part7',
                '/fnaf/2/src/resources.zip.part8',
                '/fnaf/2/src/resources.zip.part9',
                '/fnaf/2/src/resources.zip.part10',
                '/fnaf/2/src/resources.zip.part11',
                '/fnaf/2/src/resources.zip.part12',
                '/fnaf/2/src/resources.zip.part13',
                '/fnaf/2/src/resources.zip.part14',
                '/fnaf/2/src/resources.zip.part15',
                '/fnaf/2/src/resources.zip.part16',
                '/fnaf/2/src/resources.zip.part17',
                '/fnaf/2/src/resources.zip.part18',
                '/fnaf/2/src/resources.zip.part19',
                '/fnaf/2/src/resources.zip.part20',

                /* fnaf/3 */
                '/fnaf/3/index.html',
                '/fnaf/3/favicon.ico',
                '/fnaf/3/resources/vignette.png',
                '/fnaf/3/resources/title.png',
                '/fnaf/3/resources/office.png',
                '/fnaf/3/resources/launcher-text.png',
                '/fnaf/3/resources/background.gif',
                '/fnaf/3/resources/animatronic.png',
                '/fnaf/3/src/Runtime.js',
                '/fnaf/3/src/resources.zip.part1',
                '/fnaf/3/src/resources.zip.part2',
                '/fnaf/3/src/resources.zip.part3',
                '/fnaf/3/src/resources.zip.part4',
                '/fnaf/3/src/resources.zip.part5',
                '/fnaf/3/src/resources.zip.part6',
                '/fnaf/3/src/resources.zip.part7',
                '/fnaf/3/src/resources.zip.part8',
                '/fnaf/3/src/resources.zip.part9',
                '/fnaf/3/src/resources.zip.part10',
                '/fnaf/3/src/resources.zip.part11',
                '/fnaf/3/src/resources.zip.part12',
                '/fnaf/3/src/resources.zip.part13',
                '/fnaf/3/src/resources.zip.part14',
                '/fnaf/3/src/resources.zip.part15',
                '/fnaf/3/src/resources.zip.part16',
                '/fnaf/3/src/resources.zip.part17',
                '/fnaf/3/src/resources.zip.part18',
                '/fnaf/3/src/resources.zip.part19',
                '/fnaf/3/src/resources.zip.part20',

                /* fnaf/4 */
                '/fnaf/4/index.html',
                '/fnaf/4/favicon.ico',
                '/fnaf/4/resources/vignette.png',
                '/fnaf/4/resources/title.png',
                '/fnaf/4/resources/office.png',
                '/fnaf/4/resources/launcher-text.png',
                '/fnaf/4/resources/background.gif',
                '/fnaf/4/resources/animatronic.png',
                '/fnaf/4/src/Runtime.js',
                '/fnaf/4/src/resources.zip.part1',
                '/fnaf/4/src/resources.zip.part2',
                '/fnaf/4/src/resources.zip.part3',
                '/fnaf/4/src/resources.zip.part4',
                '/fnaf/4/src/resources.zip.part5',
                '/fnaf/4/src/resources.zip.part6',
                '/fnaf/4/src/resources.zip.part7',
                '/fnaf/4/src/resources.zip.part8',
                '/fnaf/4/src/resources.zip.part9',
                '/fnaf/4/src/resources.zip.part10',
                '/fnaf/4/src/resources.zip.part11',
                '/fnaf/4/src/resources.zip.part12',
                '/fnaf/4/src/resources.zip.part13',
                '/fnaf/4/src/resources.zip.part14',
                '/fnaf/4/src/resources.zip.part15',
                '/fnaf/4/src/resources.zip.part16',
                '/fnaf/4/src/resources.zip.part17',
                '/fnaf/4/src/resources.zip.part18',
                '/fnaf/4/src/resources.zip.part19',
                '/fnaf/4/src/resources.zip.part20',

                /* fnaf/ps */
                '/fnaf/ps/index.html',
                '/fnaf/ps/favicon.ico',
                '/fnaf/ps/resources/vignette.png',
                '/fnaf/ps/resources/title.png',
                '/fnaf/ps/resources/office.png',
                '/fnaf/ps/resources/launcher-text.png',
                '/fnaf/ps/resources/background.gif',
                '/fnaf/ps/resources/animatronic.png',
                '/fnaf/ps/src/Runtime.js',
                '/fnaf/ps/src/resources.zip.part1',
                '/fnaf/ps/src/resources.zip.part2',
                '/fnaf/ps/src/resources.zip.part3',
                '/fnaf/ps/src/resources.zip.part4',
                '/fnaf/ps/src/resources.zip.part5',
                '/fnaf/ps/src/resources.zip.part6',
                '/fnaf/ps/src/resources.zip.part7',
                '/fnaf/ps/src/resources.zip.part8',
                '/fnaf/ps/src/resources.zip.part9',
                '/fnaf/ps/src/resources.zip.part10',
                '/fnaf/ps/src/resources.zip.part11',
                '/fnaf/ps/src/resources.zip.part12',
                '/fnaf/ps/src/resources.zip.part13',
                '/fnaf/ps/src/resources.zip.part14',
                '/fnaf/ps/src/resources.zip.part15',
                '/fnaf/ps/src/resources.zip.part16',
                '/fnaf/ps/src/resources.zip.part17',
                '/fnaf/ps/src/resources.zip.part18',
                '/fnaf/ps/src/resources.zip.part19',
                '/fnaf/ps/src/resources.zip.part20',

                /* fnaf/sl */
                '/fnaf/sl/index.html',
                '/fnaf/sl/favicon.ico',
                '/fnaf/sl/resources/vignette.png',
                '/fnaf/sl/resources/title.png',
                '/fnaf/sl/resources/office.png',
                '/fnaf/sl/resources/launcher-text.png',
                '/fnaf/sl/resources/background.gif',
                '/fnaf/sl/resources/animatronic.png',
                '/fnaf/sl/src/Runtime.js',
                '/fnaf/sl/src/resources.zip.part1',
                '/fnaf/sl/src/resources.zip.part2',
                '/fnaf/sl/src/resources.zip.part3',
                '/fnaf/sl/src/resources.zip.part4',
                '/fnaf/sl/src/resources.zip.part5',
                '/fnaf/sl/src/resources.zip.part6',
                '/fnaf/sl/src/resources.zip.part7',
                '/fnaf/sl/src/resources.zip.part8',
                '/fnaf/sl/src/resources.zip.part9',
                '/fnaf/sl/src/resources.zip.part10',
                '/fnaf/sl/src/resources.zip.part11',
                '/fnaf/sl/src/resources.zip.part12',
                '/fnaf/sl/src/resources.zip.part13',
                '/fnaf/sl/src/resources.zip.part14',
                '/fnaf/sl/src/resources.zip.part15',
                '/fnaf/sl/src/resources.zip.part16',
                '/fnaf/sl/src/resources.zip.part17',
                '/fnaf/sl/src/resources.zip.part18',
                '/fnaf/sl/src/resources.zip.part19',
                '/fnaf/sl/src/resources.zip.part20',

                /* fnaf/ucn */
                '/fnaf/ucn/index.html',
                '/fnaf/ucn/favicon.ico',
                '/fnaf/ucn/resources/vignette.png',
                '/fnaf/ucn/resources/title.png',
                '/fnaf/ucn/resources/office.png',
                '/fnaf/ucn/resources/launcher-text.png',
                '/fnaf/ucn/resources/background.gif',
                '/fnaf/ucn/resources/animatronic.png',
                '/fnaf/ucn/src/Runtime.js',
                '/fnaf/ucn/src/resources.zip.part1',
                '/fnaf/ucn/src/resources.zip.part2',
                '/fnaf/ucn/src/resources.zip.part3',
                '/fnaf/ucn/src/resources.zip.part4',
                '/fnaf/ucn/src/resources.zip.part5',
                '/fnaf/ucn/src/resources.zip.part6',
                '/fnaf/ucn/src/resources.zip.part7',
                '/fnaf/ucn/src/resources.zip.part8',
                '/fnaf/ucn/src/resources.zip.part9',
                '/fnaf/ucn/src/resources.zip.part10',
                '/fnaf/ucn/src/resources.zip.part11',
                '/fnaf/ucn/src/resources.zip.part12',
                '/fnaf/ucn/src/resources.zip.part13',
                '/fnaf/ucn/src/resources.zip.part14',
                '/fnaf/ucn/src/resources.zip.part15',
                '/fnaf/ucn/src/resources.zip.part16',
                '/fnaf/ucn/src/resources.zip.part17',
                '/fnaf/ucn/src/resources.zip.part18',
                '/fnaf/ucn/src/resources.zip.part19',
                '/fnaf/ucn/src/resources.zip.part20',

                /* fnaf/w */
                '/fnaf/w/index.html',
                '/fnaf/w/favicon.ico',
                '/fnaf/w/resources/vignette.png',
                '/fnaf/w/resources/title.png',
                '/fnaf/w/resources/office.png',
                '/fnaf/w/resources/launcher-text.png',
                '/fnaf/w/resources/background.gif',
                '/fnaf/w/resources/animatronic.png',
                '/fnaf/w/src/Runtime.js',
                '/fnaf/w/src/resources.zip.part1',
                '/fnaf/w/src/resources.zip.part2',
                '/fnaf/w/src/resources.zip.part3',
                '/fnaf/w/src/resources.zip.part4',
                '/fnaf/w/src/resources.zip.part5',
                '/fnaf/w/src/resources.zip.part6',
                '/fnaf/w/src/resources.zip.part7',
                '/fnaf/w/src/resources.zip.part8',
                '/fnaf/w/src/resources.zip.part9',
                '/fnaf/w/src/resources.zip.part10',
                '/fnaf/w/src/resources.zip.part11',
                '/fnaf/w/src/resources.zip.part12',
                '/fnaf/w/src/resources.zip.part13',
                '/fnaf/w/src/resources.zip.part14',
                '/fnaf/w/src/resources.zip.part15',
                '/fnaf/w/src/resources.zip.part16',
                '/fnaf/w/src/resources.zip.part17',
                '/fnaf/w/src/resources.zip.part18',
                '/fnaf/w/src/resources.zip.part19',
                '/fnaf/w/src/resources.zip.part20',

                /* games/geometry dash bloodbath StreamingAssets */
                '/games/geometry dash bloodbath/StreamingAssets/audios/Bloodbath.mp3',
                '/games/geometry dash bloodbath/StreamingAssets/audios/StayInsideMe.mp3',
                '/games/geometry dash bloodbath/StreamingAssets/audios/explode.mp3',
                '/games/geometry dash bloodbath/StreamingAssets/audios/menuLoop.mp3',
                '/games/geometry dash bloodbath/StreamingAssets/audios/playSound.mp3',
                '/games/geometry dash bloodbath/StreamingAssets/audios/quitSound.mp3',

                /* games/geometry dash lite StreamingAssets */
                '/games/geometry dash lite/StreamingAssets/audios/Back On Track.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Base After Base.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Cant Let Go.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Clubstep.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Clutterfunk.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Cycles.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Dry Out.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Electrodynamix.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Electroman Adventures.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Jumper.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Polargeist.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/StayInsideMe.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Stereo Madness.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Theory of Everything.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/Time Machine.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/endStart.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/explode.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/menuLoop.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/playSound.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/quitSound.mp3',
                '/games/geometry dash lite/StreamingAssets/audios/xStep.mp3',

                /* games/geometry jump StreamingAssets */
                '/games/geometry jump/StreamingAssets/audios/1bringmeback.mp3',
                '/games/geometry jump/StreamingAssets/audios/2comgetsome.mp3',
                '/games/geometry jump/StreamingAssets/audios/3dancestuf.mp3',
                '/games/geometry jump/StreamingAssets/audios/4menu.mp3',
                '/games/geometry jump/StreamingAssets/audios/5letdothis.mp3',
                '/games/geometry jump/StreamingAssets/audios/6DarkAngel.mp3',
                '/games/geometry jump/StreamingAssets/audios/7Access.mp3',
                '/games/geometry jump/StreamingAssets/audios/8flysnake.mp3',
                '/games/geometry jump/StreamingAssets/audios/9TripleFuse.mp3',
                '/games/geometry jump/StreamingAssets/audios/10Slither.mp3',
                '/games/geometry jump/StreamingAssets/audios/11DreamCapture.mp3',
                '/games/geometry jump/StreamingAssets/audios/12DestructoDance.mp3',
                '/games/geometry jump/StreamingAssets/audios/13Cobra.mp3',
                '/games/geometry jump/StreamingAssets/audios/14Anaconda.mp3',
                '/games/geometry jump/StreamingAssets/audios/button_Click.mp3',
                '/games/geometry jump/StreamingAssets/audios/die_Audio.mp3',

                /* games/hl-main zip archives (Half-Life) */
                '/games/hl-main/halva_en_out/halva_en-0.zip',
                '/games/hl-main/halva_en_out/halva_en-1.zip',
                '/games/hl-main/halva_en_out/halva_en-2.zip',
                '/games/hl-main/halva_en_out/halva_en-3.zip',
                '/games/hl-main/halva_en_out/halva_en-4.zip',
                '/games/hl-main/halva_en_out/halva_en-5.zip',
                '/games/hl-main/halva_en_out/halva_en-6.zip',
                '/games/hl-main/halva_en_out/halva_en-7.zip',
                '/games/hl-main/halva_en_out/halva_en-8.zip',
                '/games/hl-main/halva_en_out/halva_en-9.zip',
                '/games/hl-main/halva_en_out/halva_en-10.zip',
                '/games/hl-main/halva_en_out/halva_en-11.zip',
                '/games/hl-main/halva_en_out/halva_en-12.zip',
                '/games/hl-main/halva_en_out/halva_en-13.zip',
                '/games/hl-main/halva_en_out/halva_en-14.zip',
                '/games/hl-main/halva_en_out/halva_en-15.zip',
                '/games/hl-main/halva_en_out/halva_en-16.zip',
                '/games/hl-main/halva_en_out/halva_en-17.zip',
                '/games/hl-main/halva_en_out/halva_en-18.zip',
                '/games/hl-main/halva_en_out/halva_en-19.zip',
                '/games/hl-main/halva_en_out/halva_en-20.zip',
                '/games/hl-main/halva_rus_out/halva_rus-0.zip',
                '/games/hl-main/halva_rus_out/halva_rus-1.zip',
                '/games/hl-main/halva_rus_out/halva_rus-2.zip',
                '/games/hl-main/halva_rus_out/halva_rus-3.zip',
                '/games/hl-main/halva_rus_out/halva_rus-4.zip',
                '/games/hl-main/halva_rus_out/halva_rus-5.zip',
                '/games/hl-main/halva_rus_out/halva_rus-6.zip',
                '/games/hl-main/halva_rus_out/halva_rus-7.zip',
                '/games/hl-main/halva_rus_out/halva_rus-8.zip',
                '/games/hl-main/halva_rus_out/halva_rus-9.zip',
                '/games/hl-main/halva_rus_out/halva_rus-10.zip',
                '/games/hl-main/halva_rus_out/halva_rus-11.zip',
                '/games/hl-main/halva_rus_out/halva_rus-12.zip',
                '/games/hl-main/halva_rus_out/halva_rus-13.zip',
                '/games/hl-main/halva_rus_out/halva_rus-14.zip',
                '/games/hl-main/halva_rus_out/halva_rus-15.zip',
                '/games/hl-main/halva_rus_out/halva_rus-16.zip',
                '/games/hl-main/halva_rus_out/halva_rus-17.zip',
                '/games/hl-main/halva_rus_out/halva_rus-18.zip',
                '/games/hl-main/halva_rus_out/halva_rus-19.zip',
                '/games/hl-main/halva_rus_out/halva_rus-20.zip',
                '/games/hl-main/halva_rus_out/halva_rus-21.zip',
                '/games/hl-main/halva_rus_out/halva_rus-22.zip',
                '/games/hl-main/halva_rus_out/halva_rus-23.zip',
                '/games/hl-main/halva_rus_out/halva_rus-24.zip',
                '/games/hl-main/halva_rus_out/halva_rus-25.zip',
                '/games/hl-main/halva_rus_out/halva_rus-26.zip',
                '/games/hl-main/halva_rus_out/halva_rus-27.zip',
                '/games/hl-main/halva_rus_out/halva_rus-28.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-0.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-1.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-2.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-3.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-4.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-5.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-6.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-7.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-8.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-9.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-10.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-11.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-12.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-13.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-14.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-15.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-16.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-17.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-18.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-19.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-20.zip',
                '/games/hl-main/opposing_force_en_out/opposing_force_en-21.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-0.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-1.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-2.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-3.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-4.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-5.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-6.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-7.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-8.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-9.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-10.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-11.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-12.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-13.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-14.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-15.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-16.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-17.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-18.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-19.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-20.zip',
                '/games/hl-main/opposing_force_rus_out/opposing_force_rus-21.zip',

                /* games/minecraft-classic assets */
                '/games/minecraft-classic/assets/sounds/calm1.mp3',
                '/games/minecraft-classic/assets/sounds/calm2.mp3',
                '/games/minecraft-classic/assets/sounds/calm3.mp3',
                '/games/minecraft-classic/assets/sounds/grass1.mp3',
                '/games/minecraft-classic/assets/sounds/grass2.mp3',
                '/games/minecraft-classic/assets/sounds/grass3.mp3',
                '/games/minecraft-classic/assets/sounds/grass4.mp3',
                '/games/minecraft-classic/assets/sounds/gravel1.mp3',
                '/games/minecraft-classic/assets/sounds/gravel2.mp3',
                '/games/minecraft-classic/assets/sounds/gravel3.mp3',
                '/games/minecraft-classic/assets/sounds/gravel4.mp3',
                '/games/minecraft-classic/assets/sounds/stone1.mp3',
                '/games/minecraft-classic/assets/sounds/stone2.mp3',
                '/games/minecraft-classic/assets/sounds/stone3.mp3',
                '/games/minecraft-classic/assets/sounds/stone4.mp3',
                '/games/minecraft-classic/assets/sounds/wood1.mp3',
                '/games/minecraft-classic/assets/sounds/wood2.mp3',
                '/games/minecraft-classic/assets/sounds/wood3.mp3',
                '/games/minecraft-classic/assets/sounds/wood4.mp3',
                '/games/minecraft-classic/assets/textures/background.jpg',
                '/games/minecraft-classic/assets/textures/bedrock.png',
                '/games/minecraft-classic/assets/textures/brown_mushroom.png',
                '/games/minecraft-classic/assets/textures/bush.png',
                '/games/minecraft-classic/assets/textures/button.png',
                '/games/minecraft-classic/assets/textures/button_over.png',
                '/games/minecraft-classic/assets/textures/clouds.png',
                '/games/minecraft-classic/assets/textures/color0.png',
                '/games/minecraft-classic/assets/textures/color1.png',
                '/games/minecraft-classic/assets/textures/color2.png',
                '/games/minecraft-classic/assets/textures/color3.png',
                '/games/minecraft-classic/assets/textures/color4.png',
                '/games/minecraft-classic/assets/textures/color5.png',
                '/games/minecraft-classic/assets/textures/color6.png',
                '/games/minecraft-classic/assets/textures/color7.png',
                '/games/minecraft-classic/assets/textures/color8.png',
                '/games/minecraft-classic/assets/textures/color9.png',
                '/games/minecraft-classic/assets/textures/color10.png',
                '/games/minecraft-classic/assets/textures/color11.png',
                '/games/minecraft-classic/assets/textures/color12.png',
                '/games/minecraft-classic/assets/textures/color13.png',
                '/games/minecraft-classic/assets/textures/color14.png',
                '/games/minecraft-classic/assets/textures/color15.png',
                '/games/minecraft-classic/assets/textures/crosshair.png',
                '/games/minecraft-classic/assets/textures/dirt.png',
                '/games/minecraft-classic/assets/textures/glass.png',
                '/games/minecraft-classic/assets/textures/gold.png',
                '/games/minecraft-classic/assets/textures/grass.png',
                '/games/minecraft-classic/assets/textures/grass_dirt.png',
                '/games/minecraft-classic/assets/textures/gravel.png',
                '/games/minecraft-classic/assets/textures/hotbar_bg.png',
                '/games/minecraft-classic/assets/textures/hotbar_selection.png',
                '/games/minecraft-classic/assets/textures/lava.png',
                '/games/minecraft-classic/assets/textures/leaves_opaque.png',
                '/games/minecraft-classic/assets/textures/red_flower.png',
                '/games/minecraft-classic/assets/textures/red_mushroom.png',
                '/games/minecraft-classic/assets/textures/rock.png',
                '/games/minecraft-classic/assets/textures/rock_bronze.png',
                '/games/minecraft-classic/assets/textures/rock_coal.png',
                '/games/minecraft-classic/assets/textures/rock_gold.png',
                '/games/minecraft-classic/assets/textures/sand.png',
                '/games/minecraft-classic/assets/textures/sponge.png',
                '/games/minecraft-classic/assets/textures/stevearm.png',
                '/games/minecraft-classic/assets/textures/stevehead.png',
                '/games/minecraft-classic/assets/textures/steveleg.png',
                '/games/minecraft-classic/assets/textures/stevetorso.png',
                '/games/minecraft-classic/assets/textures/stone.png',
                '/games/minecraft-classic/assets/textures/tree_side.png',
                '/games/minecraft-classic/assets/textures/tree_top.png',
                '/games/minecraft-classic/assets/textures/water.png',
                '/games/minecraft-classic/assets/textures/wood.png',
                '/games/minecraft-classic/assets/textures/yellow_flower.png',
                '/games/minecraft-classic/assets/textures/previews/2.png',
                '/games/minecraft-classic/assets/textures/previews/3.png',
                '/games/minecraft-classic/assets/textures/previews/4.png',
                '/games/minecraft-classic/assets/textures/previews/5.png',
                '/games/minecraft-classic/assets/textures/previews/6.png',
                '/games/minecraft-classic/assets/textures/previews/8.png',
                '/games/minecraft-classic/assets/textures/previews/9.png',
                '/games/minecraft-classic/assets/textures/previews/11.png',
                '/games/minecraft-classic/assets/textures/previews/12.png',
                '/games/minecraft-classic/assets/textures/previews/13.png',
                '/games/minecraft-classic/assets/textures/previews/14.png',
                '/games/minecraft-classic/assets/textures/previews/15.png',
                '/games/minecraft-classic/assets/textures/previews/16.png',
                '/games/minecraft-classic/assets/textures/previews/21.png',
                '/games/minecraft-classic/assets/textures/previews/22.png',
                '/games/minecraft-classic/assets/textures/previews/23.png',
                '/games/minecraft-classic/assets/textures/previews/24.png',
                '/games/minecraft-classic/assets/textures/previews/25.png',
                '/games/minecraft-classic/assets/textures/previews/26.png',
                '/games/minecraft-classic/assets/textures/previews/27.png',
                '/games/minecraft-classic/assets/textures/previews/28.png',
                '/games/minecraft-classic/assets/textures/previews/29.png',
                '/games/minecraft-classic/assets/textures/previews/30.png',
                '/games/minecraft-classic/assets/textures/previews/31.png',
                '/games/minecraft-classic/assets/textures/previews/32.png',
                '/games/minecraft-classic/assets/textures/previews/33.png',
                '/games/minecraft-classic/assets/textures/previews/34.png',
                '/games/minecraft-classic/assets/textures/previews/35.png',
                '/games/minecraft-classic/assets/textures/previews/36.png',
                '/games/minecraft-classic/assets/textures/previews/37.png',
                '/games/minecraft-classic/assets/textures/previews/38.png',
                '/games/minecraft-classic/assets/textures/previews/39.png',
                '/games/minecraft-classic/pack.png',

                /* games/retro-bowl missing assets */
                '/games/retro-bowl/html5game/Achievements.txt',
                '/games/retro-bowl/html5game/Charities.txt',
                '/games/retro-bowl/html5game/Colleges.txt',
                '/games/retro-bowl/html5game/LanguageUS.txt',
                '/games/retro-bowl/html5game/LanguageUS_FR.txt',
                '/games/retro-bowl/html5game/Names_F0.txt',
                '/games/retro-bowl/html5game/Names_F1.txt',
                '/games/retro-bowl/html5game/Names_L.txt',
                '/games/retro-bowl/html5game/PlayerRecords.txt',
                '/games/retro-bowl/html5game/RetroBowlHOF.txt',
                '/games/retro-bowl/html5game/Schedule17.txt',
                '/games/retro-bowl/html5game/Shopping.txt',
                '/games/retro-bowl/html5game/Teams.txt',
                '/games/retro-bowl/html5game/code.txt',
                '/games/retro-bowl/html5game/uniforms_custom_1.txt',
                '/games/retro-bowl/html5game/uniforms_default.txt',
                '/games/retro-bowl/html5game/uph_poki.js',
                '/games/retro-bowl/html5game/RetroBowl_texture_0.webp',
                '/games/retro-bowl/html5game/RetroBowl_texture_1.webp',
                '/games/retro-bowl/html5game/RetroBowl_texture_2.webp',
                '/games/retro-bowl/html5game/snd_audible.ogg',
                '/games/retro-bowl/html5game/snd_audience_dis.ogg',
                '/games/retro-bowl/html5game/snd_audience_fg.ogg',
                '/games/retro-bowl/html5game/snd_audience_idle.ogg',
                '/games/retro-bowl/html5game/snd_beep.ogg',
                '/games/retro-bowl/html5game/snd_beep2.ogg',
                '/games/retro-bowl/html5game/snd_bounce.ogg',
                '/games/retro-bowl/html5game/snd_click.ogg',
                '/games/retro-bowl/html5game/snd_drink.ogg',
                '/games/retro-bowl/html5game/snd_error.ogg',
                '/games/retro-bowl/html5game/snd_kick.ogg',
                '/games/retro-bowl/html5game/snd_oof1.ogg',
                '/games/retro-bowl/html5game/snd_oof2.ogg',
                '/games/retro-bowl/html5game/snd_oof3.ogg',
                '/games/retro-bowl/html5game/snd_post.ogg',
                '/games/retro-bowl/html5game/snd_purchase.ogg',
                '/games/retro-bowl/html5game/snd_starrating.ogg',
                '/games/retro-bowl/html5game/snd_success.ogg',
                '/games/retro-bowl/html5game/snd_tackle.ogg',
                '/games/retro-bowl/html5game/snd_throw.ogg',
                '/games/retro-bowl/html5game/snd_timeout.ogg',
                '/games/retro-bowl/js/main_unpacked.js',

                /* games/subway-surfers-ny missing assets */
                '/games/subway-surfers-ny/assets/audio/guard_catch.ogg',
                '/games/subway-surfers-ny/assets/audio/guard_proximity.ogg',
                '/games/subway-surfers-ny/assets/audio/guard_start.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_death.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_death_hitcam.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_dodge.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_foot_l.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_foot_r.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_hoverboard_crash.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_jump.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_revive.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_roll.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_sneakers_foot_l.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_sneakers_foot_r.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_sneakers_jump.ogg',
                '/games/subway-surfers-ny/assets/audio/hero_stumble.ogg',
                '/games/subway-surfers-ny/assets/audio/pickup_coin.ogg',
                '/games/subway-surfers-ny/assets/audio/pickup_powerup.ogg',
                '/games/subway-surfers-ny/assets/audio/special_jetpack.ogg',
                '/games/subway-surfers-ny/assets/audio/special_jetpack_start.ogg',
                '/games/subway-surfers-ny/assets/audio/special_magnet.ogg',
                '/games/subway-surfers-ny/assets/audio/theme.ogg',
                '/games/subway-surfers-ny/assets/audio/ui_button.ogg',
                '/games/subway-surfers-ny/assets/game/board_new_york.fbx',
                '/games/subway-surfers-ny/assets/game/board_new_york01.fbx',
                '/games/subway-surfers-ny/assets/game/board_new_york_tex_mip.png',
                '/games/subway-surfers-ny/assets/game/effects_tex_mip.png',
                '/games/subway-surfers-ny/assets/game/enemies_mip.png',
                '/games/subway-surfers-ny/assets/game/environment.fbx',
                '/games/subway-surfers-ny/assets/game/halo_mip.png',
                '/games/subway-surfers-ny/assets/game/jetpackSmoke_mip.png',
                '/games/subway-surfers-ny/assets/game/model_avatar_catch.fbx',
                '/games/subway-surfers-ny/assets/game/model_avatar_movement.fbx',
                '/games/subway-surfers-ny/assets/game/model_avatar_powerup_jet_pack.fbx',
                '/games/subway-surfers-ny/assets/game/model_avatar_powerup_pogostick.fbx',
                '/games/subway-surfers-ny/assets/game/model_avatar_start.fbx',
                '/games/subway-surfers-ny/assets/game/model_dog_catch.fbx',
                '/games/subway-surfers-ny/assets/game/model_dog_movement.fbx',
                '/games/subway-surfers-ny/assets/game/model_guard_catch.fbx',
                '/games/subway-surfers-ny/assets/game/model_guard_movement.fbx',
                '/games/subway-surfers-ny/assets/game/ocean_mip.png',
                '/games/subway-surfers-ny/assets/game/props.fbx',
                '/games/subway-surfers-ny/assets/game/shadow_mip.png',
                '/games/subway-surfers-ny/assets/game/spraySplash_mip.png',
                '/games/subway-surfers-ny/assets/game/trains.fbx',
                '/games/subway-surfers-ny/assets/idle/environment_idle.fbx',
                '/games/subway-surfers-ny/assets/idle/environment_tex_mip.png',
                '/games/subway-surfers-ny/assets/idle/jake_tex_mip.png',
                '/games/subway-surfers-ny/assets/idle/model_avatar_idle_paint.fbx',
                '/games/subway-surfers-ny/assets/idle/props_start.fbx',
                '/games/subway-surfers-ny/assets/idle/props_tex_mip.png',
                '/games/subway-surfers-ny/assets/idle/train_start_mip.png',
                '/games/subway-surfers-ny/assets/idle/trains_start.fbx',
                '/games/subway-surfers-ny/assets/idle/trains_tex_mip.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_00_brody.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_01_tagbot.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_02_tasha.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_03_ninja.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_04_lucy.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_05_king.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_07_yutani.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_08_spike.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_09_fresh.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_11_tricky.png',
                '/games/subway-surfers-ny/assets/placeholder/icon_friend.png',
                '/games/subway-surfers-ny/assets/placeholder/jake.png',

                /* games/worlds-hardest-game sounds */
                '/games/worlds-hardest-game/sounds/music.mp3',
                '/games/worlds-hardest-game/sounds/sfx_bounce0.mp3',
                '/games/worlds-hardest-game/sounds/sfx_bounce1.mp3',
                '/games/worlds-hardest-game/sounds/sfx_checkpoint.mp3',
                '/games/worlds-hardest-game/sounds/sfx_click.mp3',
                '/games/worlds-hardest-game/sounds/sfx_coin.mp3',
                '/games/worlds-hardest-game/sounds/sfx_die.mp3',
                '/games/worlds-hardest-game/sounds/sfx_intermission.mp3',
                '/games/worlds-hardest-game/sounds/sfx_win.mp3',

                /* stardew-wasm extra ContentAudio */
                '/stardew-wasm/ContentAudio.tar11',
                '/stardew-wasm/ContentAudio.tar12',
                '/stardew-wasm/ContentAudio.tar13',
                '/stardew-wasm/ContentAudio.tar14',
                '/stardew-wasm/ContentAudio.tar15',
                '/stardew-wasm/ContentAudio.tar16',
                '/stardew-wasm/ContentAudio.tar17',
                '/stardew-wasm/ContentAudio.tar18',
                '/stardew-wasm/ContentAudio.tar19',
                '/stardew-wasm/ContentAudio.tar20',
                '/stardew-wasm/ContentAudio.tar21',
                '/stardew-wasm/ContentAudio.tar22',
                '/stardew-wasm/ContentAudio.tar23',
                '/stardew-wasm/ContentAudio.tar24',
                '/stardew-wasm/stardew-valley.html',
                '/stardew-wasm/LICENSE',

                /* games/2048 extras */
                '/games/2048/2048/meta/apple-touch-icon.png',
                '/games/2048/2048/meta/apple-touch-startup-image-640x1096.png',
                '/games/2048/2048/meta/apple-touch-startup-image-640x920.png',
                '/games/2048/2048/style/fonts/ClearSans-Bold-webfont.eot',
                '/games/2048/2048/style/fonts/ClearSans-Bold-webfont.svg',
                '/games/2048/2048/style/fonts/ClearSans-Light-webfont.eot',
                '/games/2048/2048/style/fonts/ClearSans-Light-webfont.svg',
                '/games/2048/2048/style/fonts/ClearSans-Light-webfont.woff',
                '/games/2048/2048/style/fonts/ClearSans-Regular-webfont.eot',
                '/games/2048/2048/style/fonts/ClearSans-Regular-webfont.svg',

                /* games/2048m extras */
                '/games/2048m/meta/apple-touch-icon.png',
                '/games/2048m/meta/apple-touch-startup-image-640x1096.png',
                '/games/2048m/meta/apple-touch-startup-image-640x920.png',
                '/games/2048m/style/fonts/ClearSans-Bold-webfont.eot',
                '/games/2048m/style/fonts/ClearSans-Bold-webfont.svg',
                '/games/2048m/style/fonts/ClearSans-Light-webfont.eot',
                '/games/2048m/style/fonts/ClearSans-Light-webfont.svg',
                '/games/2048m/style/fonts/ClearSans-Light-webfont.woff',
                '/games/2048m/style/fonts/ClearSans-Regular-webfont.eot',
                '/games/2048m/style/fonts/ClearSans-Regular-webfont.svg',
                '/games/2048m/style/others.css',

		/* games/amongus */
		'/games/amongus/index.html',
		'/games/amongus/Build/UnityLoader.js',
		'/games/amongus/Build/AmongUSWebPortByTSProllyFinalBuild5.data.unityweb',
		'/games/amongus/Build/AmongUSWebPortByTSProllyFinalBuild5.json',
		'/games/amongus/Build/AmongUSWebPortByTSProllyFinalBuild5.wasm.code.unityweb',
		'/games/amongus/Build/AmongUSWebPortByTSProllyFinalBuild5.wasm.framework.unityweb',
		'/games/amongus/TemplateData/UnityProgress.js',
		'/games/amongus/TemplateData/favicon.ico',
		'/games/amongus/TemplateData/fullscreen.png',
		'/games/amongus/TemplateData/progressEmpty.Dark.png',
		'/games/amongus/TemplateData/progressEmpty.Light.png',
		'/games/amongus/TemplateData/progressFull.Dark.png',
		'/games/amongus/TemplateData/progressFull.Light.png',
		'/games/amongus/TemplateData/progressLogo.Dark.png',
		'/games/amongus/TemplateData/progressLogo.Light.png',
		'/games/amongus/TemplateData/style.css',
		'/games/amongus/TemplateData/webgl-logo.png',

		/* games/BirthdayBashWeb */
		'/games/BirthdayBashWeb/index.html',
		'/games/BirthdayBashWeb/Build/BirthdayBashWeb.data.001',
		'/games/BirthdayBashWeb/Build/BirthdayBashWeb.data.002',
		'/games/BirthdayBashWeb/Build/BirthdayBashWeb.framework.js',
		'/games/BirthdayBashWeb/Build/BirthdayBashWeb.loader.js',
		'/games/BirthdayBashWeb/Build/BirthdayBashWeb.wasm',

		/* games/CupheadWeb */
		'/games/CupheadWeb/index.html',
		'/games/CupheadWeb/manifest.webmanifest',
		'/games/CupheadWeb/ServiceWorker.js',
		'/games/CupheadWeb/Build/Cuphead.loader.js',
		'/games/CupheadWeb/Build/Cuphead.framework.js',
		'/games/CupheadWeb/Build/Cuphead.wasm',
		'/games/CupheadWeb/Build/Cuphead.data.001',
		'/games/CupheadWeb/Build/Cuphead.data.002',
		'/games/CupheadWeb/Build/Cuphead.data.003',
		'/games/CupheadWeb/Build/Cuphead.data.004',
		'/games/CupheadWeb/Build/Cuphead.data.005',
		'/games/CupheadWeb/Build/Cuphead.data.006',
		'/games/CupheadWeb/Build/Cuphead.data.007',
		'/games/CupheadWeb/Build/Cuphead.data.008',
		'/games/CupheadWeb/Build/Cuphead.data.009',
		'/games/CupheadWeb/Build/Cuphead.data.010',
		'/games/CupheadWeb/Build/Cuphead.data.011',
		'/games/CupheadWeb/Build/Cuphead.data.012',
		'/games/CupheadWeb/Build/Cuphead.data.013',
		'/games/CupheadWeb/Build/Cuphead.data.014',
		'/games/CupheadWeb/Build/Cuphead.data.015',
		'/games/CupheadWeb/Build/Cuphead.data.016',
		'/games/CupheadWeb/Build/Cuphead.data.017',
		'/games/CupheadWeb/Build/Cuphead.data.018',
		'/games/CupheadWeb/Build/Cuphead.data.019',
		'/games/CupheadWeb/Build/Cuphead.data.020',
		'/games/CupheadWeb/Build/Cuphead.data.021',
		'/games/CupheadWeb/Build/Cuphead.data.022',
		'/games/CupheadWeb/Build/Cuphead.data.023',
		'/games/CupheadWeb/Build/Cuphead.data.024',
		'/games/CupheadWeb/Build/Cuphead.data.025',
		'/games/CupheadWeb/Build/Cuphead.data.026',
		'/games/CupheadWeb/StreamingAssets/UnityServicesProjectConfiguration.json',
		'/games/CupheadWeb/TemplateData/style.css',
		'/games/CupheadWeb/TemplateData/favicon.ico',
		'/games/CupheadWeb/TemplateData/unity-logo-dark.png',
		'/games/CupheadWeb/TemplateData/unity-logo-light.png',
		'/games/CupheadWeb/TemplateData/progress-bar-empty-dark.png',
		'/games/CupheadWeb/TemplateData/progress-bar-empty-light.png',
		'/games/CupheadWeb/TemplateData/progress-bar-full-dark.png',
		'/games/CupheadWeb/TemplateData/progress-bar-full-light.png',
		'/games/CupheadWeb/TemplateData/icons/unity-logo-dark.png',
		'/games/CupheadWeb/TemplateData/icons/unity-logo-light.png',

		/* games/Untitled-Goose-Game */
		'/games/Untitled-Goose-Game/index.html',
		'/games/Untitled-Goose-Game/goose.png',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.loader.js',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.framework.js',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.data.part1',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.data.part2',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.data.part3',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.data.part4',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.wasm.part1',
		'/games/Untitled-Goose-Game/Build/Untitled Goose Game.wasm.part2'

		]);
		})
	);
});

self.addEventListener("activate", event => {
	// Delete any non-current cache
	event.waitUntil(
		caches.keys().then(keys => {
			return Promise.all(
				keys.map(key => {
					if (![cacheName].includes(key)) {
						return caches.delete(key);
					}
				})
			)
		})
	);
});

// Offline-first, cache-first strategy
// Kick off two asynchronous requests, one to the cache and one to the network
// If there's a cached version available, use it, but fetch an update for next time.
// Gets data on screen as quickly as possible, then updates once the network has returned the latest data. 
self.addEventListener("fetch", event => {
	event.respondWith(
		caches.open(cacheName).then(cache => {
			return cache.match(event.request).then(response => {
				return response || fetch(event.request).then(networkResponse => {
					cache.put(event.request, networkResponse.clone());
					return networkResponse;
				});
			})
		})
	);
});
